### ISSUE TITLE
Maaf Minta Solusi nyaaa ini gimana belum nemu kalo ada tutorial lebih bagus lagi

### ISSUE THREAD

**Issue by dedefajar027** [kopijahe/blog.kopijahe.my.id#9]
curl https://raw.githubusercontent.com/kopijahe/wifiid-ope
nwrt/master/scripts/kopijahe -o /tmp/kopijahe
Error loading shared library libwolfssl.so.4.8.1.66253b90: No such file or directory (needed by /usr/bin/curl)

**Comment by kopijahe** [comment]
Sudah saya tuliskan solusinya di komentar terakhir saya di #1.
